Repository NREL/HOPP, pull requests merged in 2024-10, with the labels that each got.

#359 Enhancement: Upgrade Python Infrastrucutre and Compatibility
  .github/workflows/ci.yml
  .github/workflows/conda_build.yml
  .github/workflows/publish_to_pypi.yml
  .readthedocs.yaml
  README.md
  hopp/__init__.py
  hopp/version.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: enhancement

#353 Enhancement: Upgrade ORBIT to v1.1
  .github/workflows/ci.yml
  .readthedocs.yaml
  examples/reference_plants/05-offshore-hydrogen-ca/input/plant/orbit-config-osw_15MW-ca.yaml
  greenheart/simulation/technologies/offshore/floating_platform.py
  requirements.txt
  setup.py
  tests/greenheart/test_greenheart_system.py
Labels: enhancement

#361 Bug_Fix: Property Recursion - Develop
  hopp/simulation/technologies/financial/custom_financial_model.py
Labels: bug

#367 Bug Fix: Remove erroneous package reference
  pyproject.toml
Labels: bug

#376 Fix: Remove lingering Python 3.8 references
  README.md
  docs/installation.rst
Labels: documentation

#381 Update the API URL for the NSRDB
  hopp/simulation/technologies/resource/solar_resource.py
Labels: enhancement, medium priority

#384 Bug Fix: Correct the display name of the Test PyPI Action
  .github/workflows/publish_to_test_pypi.yml
Labels: bug, low priority

#383 Remove unused dependencies
  alt_dev/Price Stats.ipynb
  alt_dev/Updating Financial Scenario.ipynb
  alt_dev/cache-analysis.ipynb
  alt_dev/optimization_driver_alt.py
  alt_dev/optimization_problem_alt.py
  alt_dev/post_dev.py
  alt_dev/run_alt.py
  docs/alt_dev/opt_driver.rst
  docs/alt_dev/opt_problem.rst
  docs/index.rst
  pyproject.toml
Labels: dependencies, high priority

#389 Update release info from past releases
  .github/workflows/ci.yml
  .github/workflows/conda_build.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/publish_to_test_pypi.yml
  .readthedocs.yaml
  README.md
  RELEASE.md
  docs/installation.rst
  pyproject.toml
Labels: documentation, high priority

#382 Clean up type_dec.py
  hopp/type_dec.py
Labels: enhancement, low priority
